// Lista de supervisores SSOMA, usada en el campo de búsqueda
// "Supervisor SSOMA a evaluar" de las encuestas Contratistas → SSOMA.
export const supervisoresSsoma = [
  'Almendra Araceli Cajamarca',
  'Amy Ysaura Ojeda',
  'Anthony Junior Jara',
  'Augusto Reyser Ulloa',
  'Billy Andersson Huarcaya',
  'Christopher Aldair Cordova',
  'Danny William Ugarte',
  'Esthefano Dioses',
  'Evert Leonidas Aquino',
  'Fiorela Sugely Terrones',
  'Jorge Martin Valdivia',
  'Juan Giordano Villacorta',
  'Julio Jhonatan Requelme',
  'Julissa Ynchi',
  'Juliana Soledad Zavaleta',
  'Karoline Giovanna Prado',
  'Katleen Pierina Paredes',
  'Luis Enrique Cabrera',
  'Miguel Angel Mendoza',
  'Miguel Gonzalo Pesantes',
  'Norhelia Huarcaya',
  'Raquel Mansilla',
  'Ronald Eduardo Vergara',
  'Victor Geovanni Quezada',
  'Victor Raul Isusqui',
  'Victoria Chavez',
  'Violeta Barrera',
]
