const encuesta = {
  id: 'contratistas-ssoma',
  titulo: 'Contratistas — SSOMA — Junio',
  descripcion: 'Evaluación de los contratistas hacia los supervisores SSOMA',
  respondedor: 'externo',
  activa: true,
  leyenda: '1 = Muy malo · 5 = Regular · 10 = Muy bueno',
  preguntas: [
    { id: 'supervisor', tipo: 'texto', texto: 'Supervisor SSOMA a evaluar', requerida: true },
    { id: 'obra', tipo: 'texto', texto: 'Obra', requerida: true },
    { id: 'p1', tipo: 'escala', texto: 'El supervisor SSOMA demuestra conocimiento técnico en seguridad y salud ocupacional', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p2', tipo: 'escala', texto: 'El supervisor SSOMA comunica de forma clara las normas y procedimientos de seguridad', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p3', tipo: 'escala', texto: 'El supervisor SSOMA está disponible y accesible cuando se necesita su apoyo', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p4', tipo: 'escala', texto: 'El supervisor SSOMA realiza inspecciones de seguridad con la frecuencia adecuada', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p5', tipo: 'escala', texto: 'El supervisor SSOMA actúa con imparcialidad y justicia ante observaciones o incidentes', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p6', tipo: 'escala', texto: 'El supervisor SSOMA brinda retroalimentación constructiva sobre el desempeño en seguridad', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p7', tipo: 'escala', texto: 'El supervisor SSOMA promueve una cultura de prevención entre los contratistas', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p8', tipo: 'escala', texto: 'El supervisor SSOMA atiende oportunamente los reportes de condiciones inseguras', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p9', tipo: 'escala', texto: 'El supervisor SSOMA respeta el trabajo del contratista y mantiene un trato profesional', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p10', tipo: 'escala', texto: 'El supervisor SSOMA explica claramente las consecuencias de incumplir las normas de seguridad', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p11', tipo: 'escala', texto: 'El supervisor SSOMA verifica que se cuente con los EPPs adecuados antes de iniciar trabajos', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p12', tipo: 'escala', texto: 'El supervisor SSOMA supervisa el correcto uso de equipos y herramientas de seguridad', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p13', tipo: 'escala', texto: 'El supervisor SSOMA gestiona adecuadamente los permisos de trabajo de alto riesgo', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p14', tipo: 'escala', texto: 'El supervisor SSOMA realiza charlas o capacitaciones de seguridad de forma efectiva', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p15', tipo: 'escala', texto: 'El supervisor SSOMA documenta y hace seguimiento a los incidentes reportados', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p16', tipo: 'escala', texto: 'El supervisor SSOMA coordina bien con los jefes de obra ante situaciones de riesgo', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p17', tipo: 'escala', texto: 'El supervisor SSOMA lidera con el ejemplo cumpliendo él mismo las normas de seguridad', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p18', tipo: 'escala', texto: 'El supervisor SSOMA responde con rapidez ante emergencias o situaciones de peligro', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p19', tipo: 'escala', texto: 'El supervisor SSOMA mantiene actualizado el registro de riesgos en el área de trabajo', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
    { id: 'p20', tipo: 'escala', texto: 'En general, ¿cómo calificarías el desempeño del supervisor SSOMA?', requerida: true, min: 1, max: 10, etiquetas: { 1: 'Muy malo', 10: 'Muy bueno' } },
  ],
}
export default encuesta
